### ISSUE TITLE
Doesn't seem to play well with jekyll-assets

### ISSUE THREAD

**Issue by chauncey-garrett** [octopress/include-tag#3]
I've been using [jekyll-assets](https://github.com/jekyll-assets/jekyll-assets) to manage my css, js, and images. After updating include-tag (  \* octopress-include-tag (1.1.3 > 1.0.3) ) the Jekyll build broke. Here's the error:

```
Liquid Exception: ReferenceError: Can't find variable: nil (in /Users/username/github/website/_assets/stylesheets/app.css) in _includes/head.html, included in ./_layouts/default.html
/Users/username/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/tags/include.rb:124:in `rescue in render': ReferenceError: Can't find variable: nil (Jekyll::Tags::IncludeTagError)
  (in /Users/username/github/website/_assets/stylesheets/app.css)
    from /Users/username/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/tags/include.rb:116:in `render'
    from /Users/username/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/octopress-include-tag-1.1.3/lib/octopress-include-tag.rb:68:in `render'
    from /Users/username/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'

...
```

This led me to the include tag for my css, which after removing, allowed for a build. Here's the tag:

``` html
{% stylesheet app media="all" type="text/css" %}
```

It seems that since `include-tag` overrides `jekyll`'s `include`, `jekyll-assets` is using `include-tag`'s `include` and thus I get the `ReferenceError: Can't find variable: nil` exception.

Is there a way around this?

**Comment by imathis** [comment]
Woah, sorry for the delayed response. I've been traveling and somehow I missed this one. I'll have a look.

**Comment by imathis** [comment]
Jekyll Assets doesn't seem to clearly extend the Include tag or register it, so I'm having trouble finding where it relies on the Include tag. For what it's worth, I'm not overwriting the include tag, just extending it and registering the new version with Liquid. Jekyll's include tag class can still be accessed at `Jekyll::Tags::IncludeTag`. If Jekyll assets wants to invoke the include tag, it's probably best to call the method `Jekyll::Tags::IncludeTag.parse`.
